linkshare_solum_bundle_demo:
  resource: "@LinkShareSolumBundle/Resources/config/routing/demo.yml"
  prefix:   /demo

linkshare_solum_bundle_test:
  resource: "@LinkShareSolumBundle/Resources/config/routing/test.yml"
  prefix:   /test