linkshare_solum_test_jslint_select_file:
    pattern:  /jslint/
    defaults: { _controller: 'LinkShareSolumBundle:Test:jsLintSelectFile' }

linkshare_solum_test_jslint_review_file:
    pattern:  /jslint/review/
    defaults: { _controller: 'LinkShareSolumBundle:Test:jsLintReviewFile' }

linkshare_solum_test_jslint_files:
    pattern:  /jslint/files/
    defaults: { _controller: 'LinkShareSolumBundle:Test:jsLintFiles' }

linkshare_solum_test_jslint_run:
    pattern:  /jslint/run/
    defaults: { _controller: 'LinkShareSolumBundle:Test:jsLintRun' }